### ISSUE TITLE
crash caused by suspected race after last file in a directory is deleted

### ISSUE THREAD

**Issue by davidqhogan** [kahing/goofys#69] opened 2016-03-16 10:23 UTC
Running 'mount' shows that the OS still considers 'files' mounted. If I then unmount and then mount files it's once again working fine.

Strangely - I have the same issue with S3FS.

Do you have any ideas? The fstab entry is as follows:

`<FULL PATH TO>/goofys#<BUCKET> <MOUNTPOINT> _netdev,noexec,allow_other,--uid=1001,--gid=1002,--dir-mode=0750,--file-mode=0640,--region=eu-west-1,--profile=<AWS CONFIG PROFILE> 0 0`

**Comment by davidqhogan** [comment] 2016-03-16 10:27
An ls on the parent directory of the mountpoint showed the following:

`# ls -l
ls: cannot access files: Transport endpoint is not connected
total 0
d????????? ? ? ? ?            ? files`

**Comment by davidqhogan** [comment] 2016-03-16 10:35
I found this in /var/log/syslog - timestamp is at the time the mountpoint appeared to fail:

`<FULL PATH TO>/goofys[848]: fuse.ERROR Ref 2 report refcnt == 0`

**Comment by kahing** [comment] 2016-03-16 17:46
seems like goofys has crashed. Do you have a complete log?

**Comment by nickschuch** [comment] 2016-03-16 23:05
Also seeing the same thing, will see if I can get a full log as well.

**Comment by davidqhogan** [comment] 2016-03-23 02:22
It happened again a couple of days ago. How can I get a complete log? That fuse error us the only thing in /var/log/syslog . I'm using up to date Ubuntu 14.04.4 LTS

**Comment by kahing** [comment] 2016-03-24 06:00
It's usually easier to log to a file if you manually mount instead of going through fstab. goofys will log to stderr if you pass it -f:

```
goofys --debug_fuse --debug_s3 -f -o allow_other --uid=1001 --gid=1002 --dir-mode=0750 --file-mode=0640 --region=eu-west-1 --profile=<AWS CONFIG PROFILE> <BUCKET> <MOUNTPOINT> >& goofys.log
```

Alternatively you can just add `--debug_fuse` and `--debug_s3` to your fstab but will generate A LOT of output to syslog.

**Comment by davidqhogan** [comment] 2016-03-31 11:45
I've captured a crash log, including a stack trace. Attached file includes output preceding the crash.

```
goroutine 52356 [running]:
panic(0x867b40, 0xc8203ce0f0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/kahing/goofys/internal.(*Inode).Ref(0xc820666240)
    /usr/local/gopath/src/github.com/kahing/goofys/internal/handles.go:77 +0x398
github.com/kahing/goofys/internal.(*Goofys).LookUpInode(0xc82000aa00, 0x7f3831ff58d0, 0xc82066ccc0, 0xc82068de10, 0x0, 0x0)
    /usr/local/gopath/src/github.com/kahing/goofys/internal/goofys.go:557 +0x121
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc82040e220, 0xc8200ba240, 0x7f3831ff58d0, 0xc82066ccc0, 0x83d700, 0xc82068de10)
    /usr/local/gopath/src/github.com/jacobsa/fuse/fuseutil/file_system.go:128 +0x2c9
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
    /usr/local/gopath/src/github.com/jacobsa/fuse/fuseutil/file_system.go:108 +0x18f
```

[goofys.crash.txt](https://github.com/kahing/goofys/files/197528/goofys.crash.txt)

**Comment by davidqhogan** [comment] 2016-03-31 11:47
I was running goofys in foreground mode, it had crashed. Running it again failed with the following message until I unmounted the mount point.

```
-----------------------------------------------------
2016/03/31 11:32:55.235230 main.FATAL Mounting file system: Mount: Statting mount point: stat <<< MOUNT POINT >>>: transport endpoint is not connected
```

**Comment by davidqhogan** [comment] 2016-04-04 13:45
Interestingly I had a subcloud (early version of s3fs) mountpoint fail in the same way this morning. Must be something to do with fuse on Ubuntu 14.04 LTS, and some assumption that subcloud, s3fs & goofys are all violating. Or just a bug in that version of fuse.

**Comment by kahing** [comment] 2016-04-05 05:56
I suspect the problem is this:

1. suppose there are objects `report/1`, `report/2`, `report/3`, goofys represents them as `report/` and files `1`, `2`, and `3` under `report/`
1. now you delete the 3 files
1. `report/` is no longer on S3
1. goofys thinks that a file was deleted without it knowing and thus some internal assumption is violated

**Comment by kahing** [comment] 2016-04-05 06:59
I am having trouble reproducing the crash. Could you describe your workload or provide a test case?

**Comment by davidqhogan** [comment] 2016-04-05 11:01
I have a bucket mounted and accessed over SFTP. The SFTP client lists the folder containing the incremental report files, then downloads & deletes each file until none remain - so I think you're probably on the track with your theory. The client connects and performs this operation every hour, and the mountpoint usually fails after a few days.

**Comment by kahing** [comment] 2016-04-06 06:38
I committed a01c2a3274bbbc9ddeb0e34e8a148ccd72247d94 which should fix your problem. Could you verify that it's fixed since I can't reproduce the problem?

**Comment by davidqhogan** [comment] 2016-04-06 06:40
Thank you! I'll deploy today and see how it goes
    _____________________________

**Comment by davidqhogan** [comment] 2016-04-09 14:13
Still working nicely a few days in, if it holds for a couple of weeks then i'd say it is fixed.

One extra detail that might help you build a regression test case for this - the files were two 'folders' deep, and nothing else was in the root folder. For example /report/incremental/1.xml, /report/incremental/2.xml , nothing in /report directly. In S3 world deleting 1.xml & 2.xml would result in both /report/incremental & /report no longer being visible because they don't really exist.

**Comment by kahing** [comment] 2016-04-11 06:58
I modified the test case in https://github.com/kahing/goofys/commit/cdae435514a1a23cb4edd2dc068579dde66bc698 to use /report/incremental, reverted the fix, and still couldn't reproduce it :-(

feel free to comment and reopen if this still happens.

**Closed by kahing** 2016-04-11 06:58 UTC
Labels: bug
