### ISSUE TITLE
UID and GID doesn't set

### ISSUE THREAD

**Issue by asims1979** [kahing/goofys#169] opened 2017-04-04 07:31 UTC
Trying to use goofys to connect to S3 (centos 7, using pre-built v0.0.10 binary). We're able to establish a connection and can copy/ls/rm files from the command line without any problem (tested as root user).

The application we're using (freeswitch) is set to save recordings to the directory mounted for S3. 
We receive the following error from the application when it tried to open the file for writing: Error Opening File [/mnt/recordings/default/innopbx.com.au/1001/msg_ff61be18-18f8-11e7-8329-13290ed4f63b.wav] [No Error.]

We've run from both fstab and command line with debug; No errors appear at all in the debug information. 

We suspect it's a permission issue. We've tried to set the uid and gid owner both via fstab:

goofys#aws-test   /mnt/shared_files fuse _netdev,allow_other,user,--file-mode=0666,user_id=996,group_id=2 0 0

(we've also tried uid= and gid= instead but that throws an Invalid argument error)

and via command line

/root/goofys --uid 996 --gid 2 --region ap-southeast-2 --debug_fuse --debug_s3 -f --dir-mode 750 --cheap --use-content-type aws-test mnt/shared_files

mount output (same for both):
aws-test on /mnt/shared_files type fuse (rw,nosuid,nodev,noexec,relatime,user_id=0,group_id=0,default_permissions,allow_other)

File ownership takes root:root user/group.

The dir-mode, gid and uid replicate the original directory's.  Even running the command line as the user we want to set the permissions to doesn't have any effect on the user_id and group_id.

What are we doing wrong?

On a side note, using S3FS works fine (the uid/gid being reporting in mount are both '0'), so we're not sure what's going on here.

**Comment by kahing** [comment] 2017-04-04 21:40
It's hard to tell without the debug logs (if you run without `-f`, it should show up in syslog), but the fstab line looks wrong:

`goofys#aws-test /mnt/shared_files fuse _netdev,allow_other,user,--file-mode=0666,user_id=996,group_id=2 0 0`

could you try someting like:

```
goofys#aws-test /mnt/shared_files fuse _netdev,allow_other,user,--file-mode=0666,--uid=996,--gid=2 0 0
```

Presumably freeswitch is running as uid=996 and gid=2?

**Comment by asims1979** [comment] 2017-04-05 01:43
Thanks for that - we've managed to get it going with your fstab entry; mount still shows gid/uid as '0', however the 'allow_other' seems to be doing its job as Freeswitch can now create and open the file

However, we've run into a new issue. It appears Freeswitch streams (or 'appends') the file as the phone call progresses. The result is that a file of 0 bytes is created, but we see a "fuse.ERROR WriteFile: only sequential writes supported" error". I've just noticed that 'Appending to a file' is not yet implemented. 

We may have to wait until that's implemented before we're able to use goofys.

**Comment by kahing** [comment] 2017-04-05 04:41
General append will probably never be supported, if freeswitch keeps appending and closing the file you likely won't get good performance regardless which s3-fs implementation you use. Could you post the output of --debug_fuse for an instance of this? Maybe there's some optimization that goofys can do to handle this particular type of IO.

**Comment by kahing** [comment] 2017-04-13 05:54
closing now, the original bug is user error and the append issue is more by design.

**Closed by kahing** 2017-04-13 05:54 UTC
