### ISSUE TITLE
Rename does not set Content-Type?

### ISSUE THREAD

**Issue by stevenbouma** [kahing/goofys#138] opened 2016-12-14 08:43 UTC
Hi,

I'm mounting using the --use-content-type flag, this works perfectly fine when a file is created with a certain extension, the Content-Type Metadata is set correctly. 
However when **renaming** a file the Content-Type is not always set, is this intended behavior? is there a way to work around this, by e.g. setting image/jpeg as the default for files without extension?

A simple example:

test.jpg (test.jpg has Content-Type: image/jpeg)

`mv ./test.jpg ./test`

(test has no extension and receives Content-Type: binary/octet-stream)

`mv ./test ./test.jpg`

(test.jpg still has Content-Type: binary/octet-stream)

**Comment by kahing** [comment] 2016-12-21 07:54
I am not able to reproduce this problem. Could you provide a test case or adapt the test I added to show the problem?

**Comment by kahing** [comment] 2017-01-28 05:57
closing as there's no update from reporter

**Closed by kahing** 2017-01-28 05:57 UTC
Labels: Need Info

**Comment by Niek** [comment] 2019-06-06 09:38
Same issue here: I have a bunch of files with the wrong content type (binary/octet-stream) because those were written before I used ``--use-content-type``. I'm trying to correct the content type by using either ``touch`` (does nothing) or rename. The content type stays the same, the only thing that works is copying to a new file, then overwrite the old file.
