### ISSUE TITLE
'mv' fails with strange file name

### ISSUE THREAD

**Issue by rektide** [kahing/goofys#162] opened 2017-03-09 00:03 UTC
Hello. Having some issues renaming a file `l├â┬╢r 006.jpg` to `myfile.jpg`.  

`mv: cannot move ‘l├â┬╢r 006.jpg’ to ‘myfile.jpg’: Permission denied`

I do have permissions on the mount and can move/copy/etc other files successfully.

The circumstances are very narrow- they only happen when using the `mv` command from a file on a mount onto that same mount. I can successfully `mv l├â┬╢r 006.jpg /tmp/myfile.jpg`, `mv /tmp/myfile.jpg l├â┬╢r 006.jpg`, or `cp l├â┬╢r 006.jpg myfile.jpg`- it's only renaming the file on the mount that doesn't work. Using a different directory on the mount is also broken- `mv l├â┬╢r 006.jpg subdir/myfile.jpg`.

I ran goofys with --debug_s3 and --debug_fuse -f and tried this mv command. Goofys yielded the following log:  
[goofys-mv-debug.txt](https://github.com/kahing/goofys/files/829321/goofys-mv-debug.txt)

**Comment by kahing** [comment] 2017-03-14 08:00
the issue is quite apparent in the log:

```
-----------------------------------------------------
2017/03/08 23:56:35.674479 s3.DEBUG DEBUG: Request s3/CopyObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
PUT http://s3.amazonaws.com/my-bucket-name/myfile.jpg HTTP/1.1
Host: s3.amazonaws.com
User-Agent: aws-sdk-go/1.0.0 (go1.7; linux; amd64)
Content-Length: 0
Authorization: xxxxxxxxxx
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Copy-Source: my-bucket-name/l├â┬╢r 006.jpg
X-Amz-Date: 20170308T235635Z
X-Amz-Metadata-Directive: REPLACE
X-Amz-Storage-Class: STANDARD
Accept-Encoding: gzip


-----------------------------------------------------
2017/03/08 23:56:35.682258 s3.DEBUG DEBUG: Response s3/CopyObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Wed, 08 Mar 2017 23:56:35 GMT
Server: AmazonS3
X-Amz-Id-2: 5Kvr58aKdiiFfo1yhGwZIuaqmWCbHXcGKLUAO5T/RHHX5FXBMdXzsei+YiTe28Ci6tzIHkpkdzI=
X-Amz-Request-Id: 90CBF72DDEC28ABF


-----------------------------------------------------
2017/03/08 23:56:35.682524 s3.DEBUG DEBUG: Validate Response s3/CopyObject failed, not retrying, error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

the copyobject request is invalid. according to https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html the string is supposed to be URL encoded. And according to https://godoc.org/github.com/aws/aws-sdk-go/service/s3#CopyObjectInput it is the client and not aws-sdk-go's responsibility to encode it.

**Comment by kahing** [comment] 2017-03-14 08:34
should be fixed! thanks for the report!

**Closed** 2017-03-14 08:33 UTC

**Comment by rektide** [comment] 2017-03-21 15:16
Many thanks for the fix! Super.
