### ISSUE TITLE
Poor parallel read performance

### ISSUE THREAD

**Issue by bgardiner** [kahing/goofys#325] opened 2018-05-24 21:06 UTC
My typical use case is to mount large [SquashFS](http://tldp.org/HOWTO/SquashFS-HOWTO/index.html) files from S3.  I have observed extremely poor performance for parallel reads of a SquashFS image mounted over goofys.  The script to demonstrate this performance is below -- as you can see it consistently takes almost 40x as long  to read the exact same set of files when attempted in parallel.  I've also shown performance for the same SquashFS mounted locally as a comparison. There is negligible difference when using the local disk, which leads me to believe this is nothing inherent about SquashFS, rather something about goofys.

Do you have any idea why parallel access would result in such performance degradation? Any suggestions on how to mitigate?

```ShellSession
$ bash -c '\
> set -e
> TIMEFORMAT=%R
> sudo mkdir -p /goofys /squash-goofys /squash-local
> sudo $GOPATH/bin/goofys --uid $(id -u) --gid $(id -g) -o allow_other spell-dev /goofys
> sudo mount /goofys/benchmarking/1mib_files.sqfs /squash-goofys
> sudo mount $HOME/benchmarking/1mib_files.sqfs /squash-local
>
>
> # run benchmark
> for i in $(seq 5); do
>   echo "running iteration $i"
>   # test reading all 1024 files in the squash via goofys sequentially
>   echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null
>   { time ls -1 /squash-goofys | xargs -I FILE dd if=/squash-goofys/FILE  of=/dev/null bs=1MB status=none ;} 2>> goofys-sequential.data
>   # test reading all 1024 files in the squash via goofys in parallel
>   echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null
>   { time ls -1 /squash-goofys | xargs -P 16 -I FILE dd if=/squash-goofys/FILE  of=/dev/null bs=1MB status=none ;} 2>> goofys-parallel.data
>   # test reading all 1024 files in the squash locally sequentially
>   echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null
>   { time ls -1 /squash-local | xargs -I FILE dd if=/squash-local/FILE  of=/dev/null bs=1MB status=none ;} 2>> local-sequential.data
>   # test reading all 1024 files in the squash locally in parallel
>   echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null
>   { time ls -1 /squash-local | xargs -P 16 -I FILE dd if=/squash-local/FILE  of=/dev/null bs=1MB status=none ;} 2>> local-parallel.data
> done
>
> echo goof-seq goof-par
> paste goofys-sequential.data goofys-parallel.data
> echo local-seq local-par
> paste local-sequential.data local-parallel.data
> '
running iteration 1
running iteration 2
running iteration 3
running iteration 4
running iteration 5
goof-seq goof-par
11.873  386.052
9.818   388.307
12.715  375.595
10.877  370.168
13.608  386.996
local-seq local-par
7.721   8.484
7.640   8.715
7.759   8.329
8.240   7.934
7.818   8.387
```

**Comment by kahing** [comment] 2018-06-03 22:51
Presumably the problem is because in your parallel test case, there's one open file which leads to all the parallel streams to collapse into random read. If that's really the cause (you can use `--debug_fuse` to confirm) then there isn't much that goofys can do. You can possibly try `--cache` mode (which requires catfs) to see if that helps, assuming you have enough disk spaces for caching.

**Comment by bgardiner** [comment] 2018-06-04 01:53
Thanks for the feedback.  I'll try with `--debug_fuse`.  I did try with `catfs` enabled (and with some much larger SquashFS images); however, I noticed that the SquashFS `mount` command would not return until the entire SquashfFS file was downloaded, which could take over 10 minutes for the size of some of the SquashFS files.  This did not happen when `catfs` was disabled. Is it expected that `catfs` will not return file operations until the entire file is resident locally on disk (instead of passing them through to goofys to be able to return while the file download is in progress)? Or is this some artifact of mounting loop devices over catfs?

**Comment by kahing** [comment] 2018-06-06 03:12
I don't think this is read ahead related. Looks like this is a problem because all the parallel sequential reads are all coming from one fd so they mangle together and become a bunch of random reads, which means we are issuing a range get instead of just keep reading from a stream. In theory, goofys could detect this and open up multiple sequential streams instead, but this seems to be a very niche use case that I am not sure if it's worth it?

**Comment by kahing** [comment] 2018-07-01 23:36
I am going to close this, since parallel read is fine, the problem is that this is not presented to us as parallel read.

**Closed by kahing** 2018-07-01 23:36 UTC
