### ISSUE TITLE
Flush() doesn't block until its done, and other IO ops can execute in between

### ISSUE THREAD

**Issue by vadirajks** [kahing/goofys#68] opened 2016-03-15 10:59 UTC
Hi Team,

looks like i have many errors and not able to figure out further.

[root@img01 bin]# grep "no such file or directory" /var/log/messages | wc -l
12844

Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df703        connection.go:476] -> Error: "invalid argument"
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df704        connection.go:395] <- GetInodeAttributes (inode 72157)
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df704        connection.go:474] -> OK
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df705        connection.go:395] <- OpenFile (inode 72157)
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df705        connection.go:474] -> OK
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df706        connection.go:395] <- ReadFile (inode 72157, handle 92893, offset 0, 4096 bytes)
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df706        connection.go:476] -> Error: "no such file or directory"
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df707        connection.go:395] <- FlushFile (inode 72157)
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df707        connection.go:474] -> OK
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df708        connection.go:395] <- ReadFile (inode 72157, handle 92893, offset 0, 4096 bytes)
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df708        connection.go:476] -> Error: "no such file or directory"
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df709        connection.go:395] <- ReleaseFileHandle
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df709        connection.go:474] -> OK
Mar 15 10:34:33 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df70a        connection.go:395] <- LookUpInode (parent 936, name "6713_sku_1280x720Padded_9caf092d7a7dd2466a5c8c215d006561.jpg")
Mar 15 10:34:34 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df70a        connection.go:476] -> Error: "no such file or directory"
Mar 15 10:34:34 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df70b        connection.go:395] <- FlushFile (inode 72157)
Mar 15 10:34:34 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df70b        connection.go:476] -> Error: "invalid argument"
Mar 15 10:34:34 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df70c        connection.go:395] <- GetInodeAttributes (inode 72157)
Mar 15 10:34:34 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df70c        connection.go:474] -> OK
Mar 15 10:34:34 img01 rsyslogd-2177: imuxsock begins to drop messages from pid 26093 due to rate-limiting
Mar 15 10:34:40 img01 rsyslogd-2177: imuxsock lost 322 messages from pid 26093 due to rate-limiting
Mar 15 10:34:40 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df750        connection.go:395] <- LookUpInode (parent 16, name "2")
Mar 15 10:34:40 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df750        connection.go:474] -> OK
Mar 15 10:34:40 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df751        connection.go:395] <- LookUpInode (parent 275, name "3")
Mar 15 10:34:40 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df751        connection.go:474] -> OK
Mar 15 10:34:40 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df752        connection.go:395] <- LookUpInode (parent 278, name "c")
Mar 15 10:34:41 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df752        connection.go:474] -> OK
Mar 15 10:34:41 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df753        connection.go:395] <- LookUpInode (parent 43060, name "6713_sku_ATOM_SIZE_MACRO_23c6d55b8d500f3bac05c71835198cea.jpg")
Mar 15 10:34:41 img01 /bin/goofys[26093]: fuse.DEBUG Op 0x003df753        connection.go:476] -> Error: "no such file or directory"

[root@img01 bin]# ./goofys --version
goofys version 0.0.5

/etc/fstab: 
goofys#size-img01 /img01 fuse _netdev,allow_other,--region='ap-southeast-1',--file-mode=0666,--debug_fuse,--debug_s3,--storage-class="REDUCED_REDUNDANCY" 0 0
                                                 
Please help me to see if anything i need to make changes.

Thanks,
Vadiraj

**Comment by kahing** [comment] 2016-03-15 19:33
These errors are not really errors. Are you trying to retrieve files that don't exist in the bucket? When an application tries to read /img01/a, goofys tries to read size-img01/a from the bucket and will return `ENOENT` to fuse, which gets translated to "no such file or directory".  I will need a more detailed explanation of what you are doing to help you further.

**Comment by vadirajks** [comment] 2016-03-22 04:43
Hi,

I sincerely apologize for taking so long to respond.

This is one of the snapshot 

I am not sure why it gives " Invalid argument" error.

[root@img01 /tmp/img01]# cp '6713/6/d/2/6713_sku_1200x627Padded_6d2cb4d35bcf65ba0e64f264b35c55c8.jpg' '/img01/6713/6/d/2/6713_sku_1200x627Padded_6d2cb4d35bcf65ba0e64f264b35c55c8.jpg'
cp: closing `/img01/6713/6/d/2/6713_sku_1200x627Padded_6d2cb4d35bcf65ba0e64f264b35c55c8.jpg': Invalid argument
[root@img01 /tmp/img01]# 

[root@img01 /tmp/img01]# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup-lv_root
                      149G   12G  130G   9% /
tmpfs                 7.8G     0  7.8G   0% /dev/shm
/dev/xvda1            485M   54M  407M  12% /boot
/tmp/img01     256P     0  256P   0% /img01
[root@img01 /tmp/img01]# 


Mar 22 04:23:24 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x0002936d        connection.go:395] <- GetInodeAttributes (inode 1)
Mar 22 04:23:24 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x0002936d        connection.go:474] -> OK
Mar 22 04:23:24 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x0002936e        connection.go:395] <- LookUpInode (parent 1, name "6713")
Mar 22 04:23:24 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x0002936e        connection.go:474] -> OK
Mar 22 04:23:24 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x0002936f        connection.go:395] <- LookUpInode (parent 64153, name "6")
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x0002936f        connection.go:474] -> OK
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029370        connection.go:395] <- LookUpInode (parent 66762, name "d")
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029370        connection.go:474] -> OK
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029371        connection.go:395] <- LookUpInode (parent 66861, name "2")
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029371        connection.go:474] -> OK
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029372        connection.go:395] <- LookUpInode (parent 66864, name "6713_sku_1200x627Padded_6d2cb4d35bcf65ba0e64f264b35c55c8.jpg")
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029372        connection.go:474] -> OK
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029373        connection.go:395] <- OpenFile (inode 66870)
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029373        connection.go:474] -> OK
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029374        connection.go:395] <- SetInodeAttributes (inode 66870, size 0)
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029374        connection.go:474] -> OK
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029375        connection.go:395] <- WriteFile (inode 66870, handle 1353, offset 0, 32279 bytes)
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029375        connection.go:474] -> OK
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029376        connection.go:395] <- FlushFile (inode 66870)
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029376        connection.go:476] -> Error: "invalid argument"
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029377        connection.go:395] <- ReleaseFileHandle
Mar 22 04:23:25 img01 /bin/goofys[21648]: fuse.DEBUG Op 0x00029377        connection.go:474] -> OK

[root@img01 /tmp/img01]# ls 6713/6/d/2/6713_sku_1200x627Padded_6d2cb4d35bcf65ba0e64f264b35c55c8.jpg -l
-rw------- 1 root root 32279 Mar 22 03:23 6713/6/d/2/6713_sku_1200x627Padded_6d2cb4d35bcf65ba0e64f264b35c55c8.jpg
[root@img01 /tmp/img01]# 

[root@img01 /tmp/img01]# ls /img01/6713/6/d/2/ | head
6713_sku_100x100_6d200284b806a7197608307797e98b23.jpg
6713_sku_100x100_6d2004ec4e33a746568dc4b828c64144.jpg
6713_sku_100x100_6d20075bbbd0877c7c1afa945834f504.jpg
6713_sku_100x100_6d200dbe511cfe75d3f8a8961fe0a2d4.jpg
6713_sku_100x100_6d201135baea6203c0e79c956f06e0b4.jpg
6713_sku_100x100_6d2015bc35ce3c94ad31f79137f42b15.jpg
6713_sku_100x100_6d201d082a5456cc7ce027faf662d058.jpg
6713_sku_100x100_6d201dffc9dfccee3d25fec84de345b8.jpg
6713_sku_100x100_6d2020542abcd384435dace68e0d883b.jpg
6713_sku_100x100_6d20215cbe3a55d02120ad042933c4a3.jpg
[root@img01 /tmp/img01]# 

Thanks,
Vadiraj

**Comment by kahing** [comment] 2016-03-24 05:55
```
 df -h
Filesystem Size Used Avail Use% Mounted on
/dev/mapper/VolGroup-lv_root
149G 12G 130G 9% /
tmpfs 7.8G 0 7.8G 0% /dev/shm
/dev/xvda1 485M 54M 407M 12% /boot
/tmp/img01 256P 0 256P 0% /img01
```

That's odd, goofys should report 1P available not 256P. The file you are copying is only 32K so it should be a normal PutObject, maybe there's an S3 error there? Can you enable --debug_s3 as well? Is it a transient error or does it always error on this file?

**Comment by vadirajks** [comment] 2016-04-01 09:23
Sorry, i have already running it in debug mode if i am not wrong and again trying to test it.

Apr  1 09:05:52 img01 /bin/goofys[7230]: s3.ERROR code=RequestError msg=send request failed, err=Head https://s3.'ap-southeast-1'.amazonaws.com/img01: dial tcp: lookup s3.'ap-southeast-1'.amazonaws.com: invalid domain name#012
Apr  1 09:05:52 img01 /bin/goofys[7230]: s3.INFO Switching from region ''ap-southeast-1'' to 'ap-southeast-1'
Apr  1 09:05:52 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000001        connection.go:395] <- init
Apr  1 09:05:52 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000001        connection.go:474] -> OK
Apr  1 09:05:52 img01 /bin/goofys[7230]: main.INFO File system has been successfully mounted.
Apr  1 09:05:53 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000002        connection.go:395] <- StatFS
Apr  1 09:05:53 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000002        connection.go:474] -> OK
Apr  1 09:07:41 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000003        connection.go:395] <- StatFS
Apr  1 09:07:41 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000003        connection.go:474] -> OK
Apr  1 09:07:41 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000004        connection.go:395] <- StatFS
Apr  1 09:07:41 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000004        connection.go:474] -> OK
Apr  1 09:07:41 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000005        connection.go:395] <- GetInodeAttributes (inode 1)
Apr  1 09:07:41 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000005        connection.go:474] -> OK

/etc/fstab:
goofys#size-img01 /img01 fuse _netdev,allow_other,--region='ap-southeast-1',--file-mode=0666,--debug_fuse,--debug_s3,--storage-class="REDUCED_REDUNDANCY" 0 0


Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000000a        connection.go:395] <- GetInodeAttributes (inode 1)
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000000a        connection.go:474] -> OK
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000000b        connection.go:395] <- LookUpInode (parent 1, name "f1")
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000000b        connection.go:476] -> Error: "no such file or directory"
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000000c        connection.go:395] <- LookUpInode (parent 1, name "f1")
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000000c        connection.go:476] -> Error: "no such file or directory"
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000000d        connection.go:395] <- CreateFile
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000000d        connection.go:474] -> OK
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000000e        connection.go:395] <- GetXattr (inode 2, name security.capability)
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000000e        connection.go:476] -> Error: "function not implemented"
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000000f        connection.go:395] <- WriteFile (inode 2, handle 1, offset 0, 17 bytes)
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000000f        connection.go:474] -> OK
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000010        connection.go:395] <- FlushFile (inode 2)
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000010        connection.go:476] -> Error: "invalid argument"
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000011        connection.go:395] <- ReleaseFileHandle
Apr  1 09:17:26 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000011        connection.go:474] -> OK
Apr  1 09:17:29 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000012        connection.go:395] <- GetInodeAttributes (inode 1)
Apr  1 09:17:29 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000012        connection.go:474] -> OK
Apr  1 09:17:29 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000013        connection.go:395] <- GetInodeAttributes (inode 2)
Apr  1 09:17:29 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000013        connection.go:474] -> OK
Apr  1 09:17:31 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000014        connection.go:395] <- OpenFile (inode 2)
Apr  1 09:17:31 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000014        connection.go:474] -> OK
Apr  1 09:17:31 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000015        connection.go:395] <- SetInodeAttributes (inode 2, size 0)
Apr  1 09:17:31 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000015        connection.go:474] -> OK
Apr  1 09:17:31 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000016        connection.go:395] <- WriteFile (inode 2, handle 2, offset 0, 17 bytes)
Apr  1 09:17:31 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000016        connection.go:474] -> OK
Apr  1 09:17:31 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000017        connection.go:395] <- FlushFile (inode 2)
Apr  1 09:17:31 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000017        connection.go:476] -> Error: "invalid argument"
Apr  1 09:17:31 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000018        connection.go:395] <- ReleaseFileHandle
Apr  1 09:17:31 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000018        connection.go:474] -> OK
Apr  1 09:17:41 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000019        connection.go:395] <- StatFS
Apr  1 09:17:41 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x00000019        connection.go:474] -> OK
Apr  1 09:17:41 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000001a        connection.go:395] <- StatFS
Apr  1 09:17:41 img01 /bin/goofys[7230]: fuse.DEBUG Op 0x0000001a        connection.go:474] -> OK


[root@img01 ~]# cp /tmp/f1 /img01/
cp: closing `/img01/f1': Invalid argument
[root@img01 ~]# cp /tmp/f1 /img01/
cp: overwrite `/img01/f1'? y
cp: closing `/img01/f1': Invalid argument

Installed :
sudo yum install golang fuse -y
[root@img01 ~]# rpm -qa | grep golang
golang-1.6-1.x86_64
[root@img01 ~]# rpm -qa | grep fuse
fuse-devel-2.8.3-4.el6.x86_64
fuse-2.8.3-4.el6.x86_64
fuse-dislocker-0.5.1-2.el6.x86_64
fuse-afp-0.8.1-6.el6.x86_64
fuse-python-0.2.1-1.el6.x86_64
fuse-libs-2.8.3-4.el6.x86_64
fuse-sshfs-2.4-1.el6.x86_64
[root@img01 ~]# 
[root@img01 ~]# cat /etc/profile.d/golang.sh 
export PATH=$PATH:/usr/local/go/bin
[root@img01 ~]# 
sudo yum update -y
export GOPATH=$HOME/go
go get github.com/kahing/goofys
go install github.com/kahing/goofys

**Comment by kahing** [comment] 2016-04-05 07:06
could you make sure that --debug_s3 is enabled? the log doesn't contain any s3 debug lines.

**Comment by vadirajks** [comment] 2016-04-07 05:57
1> --debug_s3 is not working if we use this option in /etc/fstab and it works fine if we mount from command line.
2> "That's odd, goofys should report 1P available not 256P.": either way i tried all options it will never show other than 256P and where as from s3fs mount it shows as 256T.

And again fyi , it is not showing any error after reinstalling. I have not changed anything whatever I did and mentioned before.

Thank you for all your help and support!!!!.

Regards,
Vadiraj

**Comment by vadirajks** [comment] 2016-04-07 06:17
sorry, attached debug log file and unfortunately mount got disappeared after few transaction. Please let me know if need to make any changes.

[img01-error.log.zip](https://github.com/kahing/goofys/files/207811/img01-error.log.zip)

**Comment by vadirajks** [comment] 2016-04-07 08:27
this is another round of test and i have attached log zip file for your reference.

[root@img01 ~]# goofys --debug_fuse --debug_s3 -f -o allow_other --uid=48 --gid=48 --dir-mode=0750 --file-mode=0640 --region=ap-southeast-1 img01  /img01 >> /tmp/goofys_logs.txt 2>&1 
[root@img01 ~]# 
[root@img01 ~]# mount 
/dev/mapper/VolGroup-lv_root on / type ext4 (rw)
proc on /proc type proc (rw)
sysfs on /sys type sysfs (rw)
devpts on /dev/pts type devpts (rw,gid=5,mode=620)
tmpfs on /dev/shm type tmpfs (rw)
/dev/xvda1 on /boot type ext4 (rw)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw)
img01 on /img01 type fuse (rw,nosuid,nodev,default_permissions,allow_other)
[root@img01 ~]# cd /img01
-bash: cd: /img01: Transport endpoint is not connected
[root@img01 ~]# df -h
df: `/img01': Transport endpoint is not connected
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup-lv_root
                      196G   31G  156G  17% /
tmpfs                 7.8G     0  7.8G   0% /dev/shm
/dev/xvda1            485M   80M  380M  18% /boot

**Comment by kahing** [comment] 2016-04-08 06:12
there are multiple bugs here:

```
2016/04/07 08:12:46.751146 fuse.DEBUG WriteFile 77 6787/6/6/8/6787_sku_ATOM_SIZE_MACRO_6684ba9af6031e939fbda91b2451e766.jpg [60235 499]
2016/04/07 08:12:46.751327 fuse.DEBUG FlushFile 77 6787/6/6/8/6787_sku_ATOM_SIZE_MACRO_6684ba9af6031e939fbda91b2451e766.jpg []
2016/04/07 08:12:46.751505 fuse.DEBUG WriteFile 77 6787/6/6/8/6787_sku_ATOM_SIZE_MACRO_6684ba9af6031e939fbda91b2451e766.jpg [60734 532]
```

ie: write -> flush -> write, without opening the file again. That should have triggered a non-sequential write error, but since we continued to write at the previous offset, and flush() lost out on lock/unlock, the flush didn't finish until much later so we never detected this properly. For small files in this instance it happened to work by chance, but it really could have failed.

the latter crash happened because flush improperly unlock/lock again, which caused release() to execute in between the flush, which led to the panic.

I will fix these two issues but it will result in your application fail at write/flush/write. Could you describe your application and workload so I can figure out how to mitigate this?

**Comment by vadirajks** [comment] 2016-04-08 13:40
Thank you very much for all your updates and help's.

Basically we do image re-size locally on-fly from the HTTP request and push the files to s3 using s3fs as of now. Somehow s3fs is not able to sustain the load and we wanted to move this to goofys.
Fyi, we will have many parallel hits from local system to s3 .
 
Regards,
Vadiraj

**Comment by kahing** [comment] 2016-04-08 15:16
How are you doing the image resize?

**Comment by vadirajks** [comment] 2016-04-09 04:28
we download images from http url and do image resize from imagemagick through java app. Thanks

**Comment by kahing** [comment] 2016-04-09 04:52
What's the imagemagick command thay you use? Or could you share the Java code?

**Comment by vadirajks** [comment] 2016-04-09 05:31
i am sorry, i will not be able to share the code.

**Comment by vadirajks** [comment] 2016-04-09 05:37
http://www.imagemagick.org/script/convert.php
http://www.imagemagick.org/script/index.php

[root@img01 ~]# ps aux | grep convert
root     10629  7.2  0.0 393020  6584 ?        Sl   05:34   0:00 convert /img01/6721/a/d/8/6721_sku_ATOM_SIZE_MACRO_ad8e61ab0ff38ec6fbc5fefd4cfa2ca9.jpg -resize 460x460 -gravity center -extent 460x460 /img01/6721/a/d/8/6721_sku_460x460Padded_ad8e61ab0ff38ec6fbc5fefd4cfa2ca9.jpg
root     10630  8.1  0.0 400580 14328 ?        Sl   05:34   0:00 convert /img01/6721/f/0/9/6721_sku_ATOM_SIZE_MACRO_f09ba1a04c0ef8ca0c0bda02665e8f9c.jpg -resize 1200x800 -gravity center -extent 1200x800 /img01/6721/f/0/9/6721_sku_1200x800Padded_f09ba1a04c0ef8ca0c0bda02665e8f9c.jpg
root     10633  8.6  0.0 398380 12084 ?        Sl   05:34   0:00 convert /img01/6721/b/9/6/6721_sku_ATOM_SIZE_MACRO_b9632fde899be9cf62f2e697c163a7bf.jpg -resize 1200x627 -gravity center -extent 1200x627 /img01/6721/b/9/6/6721_sku_1200x627Padded_b9632fde899be9cf62f2e697c163a7bf.jpg
root     10635  7.8  0.0 390856  4504 ?        Sl   05:34   0:00 convert /img01/6721/f/9/d/6721_sku_ATOM_SIZE_MACRO_f9d3fa6d64114ca2b2e9aca1e5e788cb.jpg -resize 100x100 /img01/6721/f/9/d/6721_sku_100x100_f9d3fa6d64114ca2b2e9aca1e5e788cb.jpg
root     10638  8.7  0.0 393016  6592 ?        Sl   05:34   0:00 convert /img01/6721/2/1/6/6721_sku_ATOM_SIZE_MACRO_216cb59071574f2446694ee39e9f0724.jpg -resize 460x460 -gravity center -extent 460x460 /img01/6721/2/1/6/6721_sku_460x460Padded_216cb59071574f2446694ee39e9f0724.jpg
root     10710  0.0  0.0 103248   872 pts/0    S+   05:35   0:00 grep convert
[root@img01 ~]# 

Thanks,
Vadiraj

**Comment by kahing** [comment] 2016-04-11 06:45
I picked a few of the commands and used a random jpg that I have lying around and they all worked even after https://github.com/kahing/goofys/commit/bf6e5f8c2c25c9a35753b44ac6786f788da6bfb7 . Could you retry?

**Comment by vadirajks** [comment] 2016-04-25 08:45
[goofys_logs.txt.gz](https://github.com/kahing/goofys/files/234162/goofys_logs.txt.gz)
no it didn’t help . Please check the attached log file . ThankYou

**Comment by kahing** [comment] 2016-04-27 06:08
can you describe what's going on and try to minimize the steps to reproduce? It's hard to figure out what's going on with a 2 million lines log file.

**Comment by kahing** [comment] 2016-08-18 05:17
closing due to lack of info

**Closed by kahing** 2016-08-18 05:17 UTC
Labels: bug, Need Info
