### ISSUE TITLE
Problems with gzip files

### ISSUE THREAD

**Issue by cavanaug** [kahing/goofys#147] opened 2017-01-28 00:28 UTC
If I have a file in s3 compressed in gzip goofys has a problem handling it.

Specifically for example 

s3 file 5849185072F1476A0464CA52-1-2017-01-19-00-01-24-094e92dd-db38-4d0c-94ef-f00af06e9008.gz
with properties of 
    {
      Key: "/5849185072F1476A0464CA52-1-2017-01-19-00-01-24-094e92dd-db38-4d0c-94ef-f00af06e9008.gz",
      LastModified: 2017-01-19 00:11:27 +0000 UTC,
      Owner: {
      },
      Size: 4659125,
      StorageClass: "STANDARD"
    },

The file however in goofys doesnt show the file as gzipped, instead it shows me the first 4659125 characters of the gzunziped version of the file.

--
John Cavanaugh

**Comment by kahing** [comment] 2017-01-28 05:54
How are you reading the file? I am not able to reproduce this

**Comment by kahing** [comment] 2017-01-28 05:56
specifically, here's what I did:
```
$ cp /home/khc/Downloads/surefire.tar.gz /tmp/mnt/
$ # restart goofys to make sure VFS cache is cleared
$ md5sum /home/khc/Downloads/surefire.tar.gz
91b52a165eb4bcb846b83c748f0989c7  /home/khc/Downloads/surefire.tar.gz
$ md5sum /tmp/mnt/surefire.tar.gz
91b52a165eb4bcb846b83c748f0989c7  /tmp/mnt/surefire.tar.gz
```

**Comment by cavanaug** [comment] 2017-01-28 06:09
Here is a log of my commands...

┌─[22:04:33]─[cavanaug@jc-zbook17w
:~/goofys/cscrpds-prod-mq-landing/prod/firehose/v1/1A20/5849185072F1476A0464CA52/2017/01/28/01]
└──>> aws s3 ls
s3://cscrpds-prod-mq-landing/prod/firehose/v1/1A20/5849185072F1476A0464CA52/2017/01/28/01/
2017-01-27 17:16:31    3580552
5849185072F1476A0464CA52-1-2017-01-28-01-06-28-bb76276c-1962-40e4-96e3-d8072573f479.gz
2017-01-27 17:26:33    3449806
5849185072F1476A0464CA52-1-2017-01-28-01-16-29-146ba0c8-247d-40cf-8adf-8015cb4da992.gz
2017-01-27 17:36:35    3375120
5849185072F1476A0464CA52-1-2017-01-28-01-26-31-10352211-c7e9-4d46-bbb5-2cca278b04af.gz
2017-01-27 17:46:36    3983537
5849185072F1476A0464CA52-1-2017-01-28-01-36-33-0e834b08-3843-4168-b830-4139790682e3.gz
2017-01-27 17:56:40    3351748
5849185072F1476A0464CA52-1-2017-01-28-01-46-38-e453f19a-7243-4d21-b269-bc8bd0ecef82.gz
2017-01-27 18:06:41    3300680
5849185072F1476A0464CA52-1-2017-01-28-01-56-39-d333810d-f135-4c4c-bed6-d39731a7a4a6.gz

┌─[22:04:54]─[cavanaug@jc-zbook17w
:~/goofys/cscrpds-prod-mq-landing/prod/firehose/v1/1A20/5849185072F1476A0464CA52/2017/01/28/01]
└──>> ls -l
total 20550
-rw-r--r-- 1 cavanaug cavanaug 3580552 Jan 27 17:16
5849185072F1476A0464CA52-1-2017-01-28-01-06-28-bb76276c-1962-40e4-96e3-d8072573f479.gz
-rw-r--r-- 1 cavanaug cavanaug 3449806 Jan 27 17:26
5849185072F1476A0464CA52-1-2017-01-28-01-16-29-146ba0c8-247d-40cf-8adf-8015cb4da992.gz
-rw-r--r-- 1 cavanaug cavanaug 3375120 Jan 27 17:36
5849185072F1476A0464CA52-1-2017-01-28-01-26-31-10352211-c7e9-4d46-bbb5-2cca278b04af.gz
-rw-r--r-- 1 cavanaug cavanaug 3983537 Jan 27 17:46
5849185072F1476A0464CA52-1-2017-01-28-01-36-33-0e834b08-3843-4168-b830-4139790682e3.gz
-rw-r--r-- 1 cavanaug cavanaug 3351748 Jan 27 17:56
5849185072F1476A0464CA52-1-2017-01-28-01-46-38-e453f19a-7243-4d21-b269-bc8bd0ecef82.gz
-rw-r--r-- 1 cavanaug cavanaug 3300680 Jan 27 18:06
5849185072F1476A0464CA52-1-2017-01-28-01-56-39-d333810d-f135-4c4c-bed6-d39731a7a4a6.gz

┌─[22:04:58]─[cavanaug@jc-zbook17w
:~/goofys/cscrpds-prod-mq-landing/prod/firehose/v1/1A20/5849185072F1476A0464CA52/2017/01/28/01]
└──>> aws s3 cp
s3://cscrpds-prod-mq-landing/prod/firehose/v1/1A20/5849185072F1476A0464CA52/2017/01/28/01/5849185072F1476A0464CA52-1-2017-01-28-01-06-28-bb76276c-1962-40e4-96e3-d8072573f479.gz
/tmp/aws_cli_file
download:
s3://cscrpds-prod-mq-landing/prod/firehose/v1/1A20/5849185072F1476A0464CA52/2017/01/28/01/5849185072F1476A0464CA52-1-2017-01-28-01-06-28-bb76276c-1962-40e4-96e3-d8072573f479.gz
to ../../../../../../../../../../../../../tmp/aws_cli_file

┌─[22:05:37]─[cavanaug@jc-zbook17w
:~/goofys/cscrpds-prod-mq-landing/prod/firehose/v1/1A20/5849185072F1476A0464CA52/2017/01/28/01]
└──>> file /tmp/aws_cli_file
/tmp/aws_cli_file: gzip compressed data, from FAT filesystem (MS-DOS, OS/2,
NT)

┌─[22:05:47]─[cavanaug@jc-zbook17w
:~/goofys/cscrpds-prod-mq-landing/prod/firehose/v1/1A20/5849185072F1476A0464CA52/2017/01/28/01]
└──>> cp
5849185072F1476A0464CA52-1-2017-01-28-01-06-28-bb76276c-1962-40e4-96e3-d8072573f479.gz
/tmp/goofys_file

┌─[22:06:14]─[cavanaug@jc-zbook17w
:~/goofys/cscrpds-prod-mq-landing/prod/firehose/v1/1A20/5849185072F1476A0464CA52/2017/01/28/01]
└──>> file /tmp/goofys_file
/tmp/goofys_file: ASCII text, with very long lines

┌─[22:06:20]─[cavanaug@jc-zbook17w
:~/goofys/cscrpds-prod-mq-landing/prod/firehose/v1/1A20/5849185072F1476A0464CA52/2017/01/28/01]
└──>> ls -l /tmp/goofys_file /tmp/aws_cli_file
-rw-r--r-- 1 cavanaug cavanaug 3580552 Jan 27 17:16 /tmp/aws_cli_file
-rw-r--r-- 1 cavanaug cavanaug 3580552 Jan 27 22:06 /tmp/goofys_file

┌─[22:06:30]─[cavanaug@jc-zbook17w
:~/goofys/cscrpds-prod-mq-landing/prod/firehose/v1/1A20/5849185072F1476A0464CA52/2017/01/28/01]
└──>> md5sum /tmp/goofys_file /tmp/aws_cli_file
499a436a3fa65f9a436e9f648d4386ff  /tmp/goofys_file
cc28920f81cf81a7b5cb799f3cf6adf6  /tmp/aws_cli_file

**Comment by kahing** [comment] 2017-01-28 06:57
could you include debug log from --debug_s3? also, is there a way for me to reproduce this?

**Comment by kahing** [comment] 2017-01-28 07:13
also, is this aws s3? If not, what is it?

**Comment by cavanaug** [comment] 2017-01-30 21:39
Ill setup an s3 bucket for you with this data for a repro later tonight.

Yes it is the aws cli tool.

**Comment by cavanaug** [comment] 2017-01-30 21:55
Actually I had a meeting cancelled so I just did it now.

I setup the permissions so anyone with a valid aws account (which I presume
you do) should be able to access the following.

Try bucket cscrpds-publicshare in us-west-2

Try any of the leaf node files.   They will be improperly truncated with
goofys but ok in the s3 web ui.


On Mon, Jan 30, 2017 at 1:39 PM, John Cavanaugh <cavanaughwww+misc@gmail.com

**Comment by kahing** [comment] 2017-01-31 06:00
looks like I can't head those objects:

```
$ aws s3 cp s3://cscrpds-publicshare/2017/01/17/18/57DB34750AC4EA0F0A442EAD-1-2017-01-17-18-30-26-099482db-a39a-4ebb-a1a0-e66a288b45fc.gz /tmp/
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by cavanaug** [comment] 2017-01-31 08:44
Ill create some keys for you tomorrow while im in the office.  Sorry, I
thought the permissions would work.

**Comment by kahing** [comment] 2017-02-02 05:06
any updates? I want to cut a new release this week?

**Comment by cavanaug** [comment] 2017-02-02 06:27
I sent you an email to your private address with some keys to try it.

**Comment by kahing** [comment] 2017-02-02 06:32
got it. So this is fixed by c37026b, I wasn't able to reproduce it because the objects I tried didn't have content-encoding set.

**Comment by kahing** [comment] 2017-02-02 06:32
could you confirm if the fix works for you?

**Closed by kahing** 2017-02-02 06:32 UTC

**Comment by cavanaug** [comment] 2017-02-02 06:58
Let me work on building it and trying it...

Thanks for being so responsive.  You rock!!

**Comment by cavanaug** [comment] 2017-02-02 07:08
I just built the latest version and it works.   Thanks!!!

On Wed, Feb 1, 2017 at 10:58 PM, John Cavanaugh <cavanaughwww+misc@gmail.com
