### ISSUE TITLE
Files and Directories shows wrong

### ISSUE THREAD

**Issue by sIrKicK** [kahing/goofys#319] opened 2018-05-04 08:33 UTC
Hello,
im testing goofys vs s3fs and the access to directories and listing is so much faster, i need faster acces to listing diretories because my bucket contain more than 300thousand of dirs.. but i have a lot of problems with the names containing # ! and characters non alphanumeric. It showns like:

Real -> folder#1#
Shows -> folder%231%23

and when i enter in folder%231%23 the dir is empty.

Does anyone have the same problem?
how can i solve it.. 

Thanks!

**Comment by sIrKicK** [comment] 2018-05-04 08:34
I mount the bucket with this command: 

goofys --region eu-west-1 bucket-name:/remotedir localdir

**Comment by sIrKicK** [comment] 2018-05-14 16:28
Can anybody help me with this?

**Comment by kahing** [comment] 2018-07-01 23:16
This was a regression on the unreleased goofys on master, but thanks for catching it!

**Comment by cr-solutions** [comment] 2018-07-05 12:02
Hello kahing,

we have the same problem. 
In this case, we can also not use the rm command in bash and ProFTPd have also problems deleting files.
Currently we blocking now special chars like space, umlaute ...
But this is not a good user experience for our customers.

Sample:
_Hello World.jpg_ is seen with goofys as _Hello+World.jpg_

but rm Hello+World.jpg not works. 
rm _"Hello World.jpg"_ works.

How to get a new version with your fix?

go get github.com/kahing/goofys
go install github.com/kahing/goofys

return the old one!

Thanks in advance,
best
Ricardo

**Comment by kahing** [comment] 2018-07-08 21:48
`go get -u github.com/kahing/goofys`

**Comment by kahing** [comment] 2018-07-08 21:48
I am closing this since I believe master resolves the problem.

**Closed by kahing** 2018-07-08 21:48 UTC
