### ISSUE TITLE
About get object with Range 

### ISSUE THREAD

**Issue by limbo127** [kahing/goofys#114] opened 2016-09-23 16:49 UTC
Hello,
We are using goofys with very big file : ~ 20 G 
We are using mmap() on this file and then we do a lot of memcpy of block < 128K.
We are observing a lot of big range request on S3 bucket, ~ 5M  compare to 128K maximum.
Can you explain how get object with http range are done with goofys ?

Regards, 
Nicolas Prochazka

**Comment by kahing** [comment] 2016-09-25 03:01
When goofys detects that a file is being read sequentially (which is defined as 5MB of sequential read), goofys switches to readahead mode which prefetches the next 100MB in 20MB chunks. This allows us to read the object in parallel and speed up the read. See #21 for some background information.

Is that not working well for you?

**Comment by limbo127** [comment] 2016-09-25 17:04
Yes it is a problem for us. We are using raw image of filesystem so read
block is rarely sequencially, can we disable it ?
Regards,
Nicolas prochazka.

**Comment by kahing** [comment] 2016-09-25 17:33
How are you reading the raw filesystem images? goofys only goes into this mode if you already read 5MB sequentially. Could you describe the use case a bit more?

**Comment by limbo127** [comment] 2016-09-25 17:56
Typical use is very simple, Linux mmap file of 20g, then read block of size
from 8ko to 128ko, not sequentially, we are observing lot of 5mo chunk from
sdk/go on s3 log file
Regards,
Nicolas

Le dimanche 25 septembre 2016, Ka-Hing Cheung <notifications@github.com> a
écrit :

**Comment by kahing** [comment] 2016-09-25 18:23
could you try the latest commit to see if that addresses the problem for you? goofys could still have some positives but we should fallback to doing regular GET quickly.

Note that since you are doing random read, performance will be quite bad since each read will map to a separate GET request. S3 isn't really designed for this use case.

**Comment by limbo127** [comment] 2016-09-26 12:15
hello,
i'm trying to compile from last commit, but when i try to mount bucket
nothing .

./goofys --debug_fuse --debug_s3 --region eu-west-1 xxx /aws2/
no debug
[root@retd bin]# ls /aws2/
no mount point

Regards,
Nicolas


2016-09-25 20:23 GMT+02:00 Ka-Hing Cheung <notifications@github.com>:

**Comment by kahing** [comment] 2016-09-26 15:47
By default log goes to syslog unless you use -f
On Sep 26, 2016 5:15 AM, limbo127 <notifications@github.com> wrote:hello,
i'm trying to compile from last commit, but when i try to mount bucket
nothing .

./goofys --debug_fuse --debug_s3 --region eu-west-1 xxx /aws2/
no debug
[root@retd bin]# ls /aws2/
no mount point

Regards,
Nicolas


2016-09-25 20:23 GMT+02:00 Ka-Hing Cheung <notifications@github.com>:

**Comment by limbo127** [comment] 2016-09-26 17:00
sorry,
[root@retd bin]# ./goofys -f  --profile logger --region eu-west-1 xxxx
/aws2/
2016/09/26 18:59:25.809219 s3.INFO Unable to detect bucket region, using
'us-east-1'
2016/09/26 18:59:25.809369 s3.INFO Falling back to v2 signer
2016/09/26 18:59:25.982517 main.ERROR Unable to access 'xxxx:
BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region
2016/09/26 18:59:25.982581 main.FATAL Mounting file system: Mount:
initialization failed

it's working with 0.7 .
Regards,
Nicolas



2016-09-26 17:47 GMT+02:00 Ka-Hing Cheung <notifications@github.com>:

**Comment by kahing** [comment] 2016-09-27 04:38
I can reproduce this issue with a bucket name that contains `.`

**Comment by kahing** [comment] 2016-09-27 06:05
Could you try again with 780f54bf0581cf05c8dd42da0d2373b163fbdc8c?

**Comment by limbo127** [comment] 2016-09-27 06:14
Yes, my bucket contains .
Regards
Nicolas

2016-09-27 6:38 GMT+02:00 Ka-Hing Cheung <notifications@github.com>:

**Comment by kahing** [comment] 2016-09-28 18:39
is master working for you now?

**Comment by limbo127** [comment] 2016-09-28 19:13
Yes it 's ok for region parameter,,
but I have not yet test the big range request issue, I hope to do tomorrow.
Regards,
Nicolas

2016-09-28 20:39 GMT+02:00 Ka-Hing Cheung <notifications@github.com>:

**Comment by limbo127** [comment] 2016-09-30 08:14
Hello again,
With debug_s3 we cannot see range request log , or data receive, is it
possible to add them into debug mode ?
With debug_fuse, we can see our 32k block read appear as 128Ko on fuse
debug, is it a normal behaviour ?

Regards,
Nicolas

2016-09-28 21:13 GMT+02:00 nicolas prochazka <prochazka.nicolas@gmail.com>:

**Comment by kahing** [comment] 2016-10-01 00:36
I am not sure why the request range doesn't show up in debug either, probably because aws-sdk-go doesn't include it.

For read size, could you try manually changing maxReadAhead in https://github.com/jacobsa/fuse/blob/master/connection.go#L56

**Comment by limbo127** [comment] 2016-10-04 21:26
Hello again, 
Tests seems to be not conclusive, we are observing big paquet compare to our small read. 
With s3log that are not in realtime, it's very difficult to give a complete use case, log complete s3 range request from goofys will be a good thing.
Regards

**Comment by kahing** [comment] 2016-10-04 22:03
Are you sure s3 is the right solution for you if you worry about this? The per request cost and latency likely overwhelms the cost and latency caused by read-amplification.

**Comment by limbo127** [comment] 2016-10-05 07:01
Yes it works as we want execpt for goofys <-> S3 consumption
our client <---- good latency / bandwitch ---> EC2 VM goofys <---- big
bandwitch cause by big read range  request ?----> S3
Regards,


2016-10-05 0:03 GMT+02:00 Ka-Hing Cheung <notifications@github.com>:

**Comment by limbo127** [comment] 2016-10-05 21:01
Hello, 
in Handles.go , line 836, we can read : if offset != 0 {
bytes := fmt.Sprintf("bytes=%v-", offset)
In this case, If the last-byte-pos  value of range request  is absent, or if the value is greater than or equal to the current length of the entity-body, last-byte-pos is taken to be equal to one less than the current length of the entity- body in bytes

my question is , how body size is calculating ?   is it possible to add block read size + offset ?
Regards, 
Nicolas

**Comment by kahing** [comment] 2016-10-07 05:15
It's possible, but may not be desired since most people use goofys for streaming workload. Maybe you can try this locally and report back how much of a difference it makes? I can be convinced by a good benchmark.

you can probably use `len(buf)+offset-1` as the last-byte-pos.

**Comment by limbo127** [comment] 2016-10-07 05:59
ok,
thanks for this explanation
Regards,
NIcolas

2016-10-07 7:15 GMT+02:00 Ka-Hing Cheung <notifications@github.com>:

**Comment by kahing** [comment] 2016-10-13 05:14
closing this for now. I think this usage is out of goofys' scope. Happy to help you further though

**Closed by kahing** 2016-10-13 05:14 UTC
