### ISSUE TITLE
Occur errors when move a huge file to goofys mount point

### ISSUE THREAD

**Issue by jindov** [kahing/goofys#47] opened 2015-12-17 02:42 UTC
Hi Kahing,

I successfully write files to goofys mount point but if I write a huge file to this mount point, it's error:

my file is about 70GB or more

```
panic: invalid part number: 10001

goroutine 1659259 [running]:
github.com/kahing/goofys/internal.(*FileHandle).mpuPartNoSpawn(0xc8202d01a0, 0xc8200ae400, 0xc823ba2000, 0x500000, 0x500000, 0x2711, 0x0, 0x0)
        /opt/go/src/github.com/kahing/goofys/internal/handles.go:383 +0xa68
github.com/kahing/goofys/internal.(*FileHandle).mpuPart(0xc8202d01a0, 0xc8200ae400, 0xc823ba2000, 0x500000, 0x500000, 0x2711)
        /opt/go/src/github.com/kahing/goofys/internal/handles.go:424 +0xca
created by github.com/kahing/goofys/internal.(*FileHandle).WriteFile
        /opt/go/src/github.com/kahing/goofys/internal/handles.go:492 +0x919

goroutine 1 [select, 19 minutes]:
github.com/jacobsa/fuse.(*MountedFileSystem).Join(0xc820146630, 0x7fbbc5e40b08, 0xc8200103e0, 0x0, 0x0)
        /opt/go/src/github.com/jacobsa/fuse/mounted_file_system.go:42 +0x167
main.main.func1(0xc8200cc6c0)
        /opt/go/src/github.com/kahing/goofys/main.go:200 +0x8b5
github.com/codegangsta/cli.(*App).Run(0xc8200cc5a0, 0xc82000a090, 0x9, 0x9, 0x0, 0x0)
        /opt/go/src/github.com/codegangsta/cli/app.go:180 +0x1051
main.main()
        /opt/go/src/github.com/kahing/goofys/main.go:209 +0xf6

goroutine 17 [syscall, 19 minutes, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, 19 minutes]:
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/lib/golang/src/os/signal/signal_unix.go:28 +0x37

goroutine 21 [semacquire]:
sync.runtime_Syncsemacquire(0xc820170280)
        /usr/lib/golang/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc820170270)
        /usr/lib/golang/src/sync/cond.go:62 +0x9b
io.(*pipe).read(0xc820170240, 0xc820240558, 0xaa8, 0xaa8, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc820148028, 0xc820240558, 0xaa8, 0xaa8, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/io/pipe.go:134 +0x50
bufio.(*Scanner).Scan(0xc826133f10, 0xc826133eb8)
        /usr/lib/golang/src/bufio/scan.go:180 +0x877
github.com/Sirupsen/logrus.(*Logger).writerScanner(0xc820014820, 0xc820148028)
        /opt/go/src/github.com/Sirupsen/logrus/writer.go:20 +0x129
created by github.com/Sirupsen/logrus.(*Logger).Writer
        /opt/go/src/github.com/Sirupsen/logrus/writer.go:12 +0x17b

goroutine 20 [semacquire, 19 minutes]:
sync.runtime_Syncsemacquire(0xc8201701c0)
        /usr/lib/golang/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc8201701b0)
        /usr/lib/golang/src/sync/cond.go:62 +0x9b
io.(*pipe).read(0xc820170180, 0xc82023e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc820148018, 0xc82023e000, 0x1000, 0x1000, 0x43c654, 0x0, 0x0)
        /usr/lib/golang/src/io/pipe.go:134 +0x50
bufio.(*Scanner).Scan(0xc820036730, 0x1000)
        /usr/lib/golang/src/bufio/scan.go:180 +0x877
github.com/Sirupsen/logrus.(*Logger).writerScanner(0xc820172190, 0xc820148018)
        /opt/go/src/github.com/Sirupsen/logrus/writer.go:20 +0x129
created by github.com/Sirupsen/logrus.(*Logger).Writer
        /opt/go/src/github.com/Sirupsen/logrus/writer.go:12 +0x17b

goroutine 66 [syscall]:
syscall.Syscall(0x0, 0x8, 0xc8202a4018, 0x21000, 0xc81fdb9961, 0x0, 0x411766)
        /usr/lib/golang/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x8, 0xc8202a4018, 0x21000, 0x21000, 0xc820153680, 0x0, 0x0)
        /usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x8, 0xc8202a4018, 0x21000, 0x21000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc82024c008, 0xc8202a4018, 0x21000, 0x21000, 0xa6eb30, 0x0, 0x0)
        /usr/lib/golang/src/os/file_unix.go:211 +0x53
os.(*File).Read(0xc82024c008, 0xc8202a4018, 0x21000, 0x21000, 0x411766, 0x0, 0x0)
        /usr/lib/golang/src/os/file.go:95 +0x8a
github.com/jacobsa/fuse/internal/buffer.(*InMessage).Init(0xc8202a4000, 0x7fbbc5e40270, 0xc82024c008, 0x0, 0x0)
        /opt/go/src/github.com/jacobsa/fuse/internal/buffer/in_message.go:53 +0xa2
github.com/jacobsa/fuse.(*Connection).readMessage(0xc820252000, 0xc8202a4000, 0x0, 0x0)
        /opt/go/src/github.com/jacobsa/fuse/connection.go:317 +0x7a
github.com/jacobsa/fuse.(*Connection).ReadOp(0xc820252000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/go/src/github.com/jacobsa/fuse/connection.go:379 +0x81
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps(0xc820144420, 0xc820252000)
        /opt/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:98 +0x53
github.com/jacobsa/fuse.Mount.func1(0x7fbbc2e16390, 0xc820144420, 0xc820252000, 0xc820148038)
        /opt/go/src/github.com/jacobsa/fuse/mount.go:89 +0x35
created by github.com/jacobsa/fuse.Mount
        /opt/go/src/github.com/jacobsa/fuse/mount.go:92 +0x827

goroutine 67 [select, 19 minutes, locked to thread]:
runtime.gopark(0xa721d8, 0xc82003c728, 0x987558, 0x6, 0x42e718, 0x2)
        /usr/lib/golang/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82003c728, 0x0, 0x18)
        /usr/lib/golang/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82003c728)
        /usr/lib/golang/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/lib/golang/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1

goroutine 68 [chan receive, 19 minutes]:
main.registerSIGINTHandler.func1(0xc820192300, 0x7fffca03389b, 0x9)
        /opt/go/src/github.com/kahing/goofys/main.go:53 +0x87
created by main.registerSIGINTHandler
        /opt/go/src/github.com/kahing/goofys/main.go:64 +0x17f

goroutine 1659054 [IO wait]:
net.runtime_pollWait(0x7fbbc5e41c98, 0x72, 0xc8200101e0)
        /usr/lib/golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8248ef410, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8248ef410, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8248ef3b0, 0xc820128000, 0x1000, 0x1000, 0x0, 0x7fbbc5e3c050, 0xc8200101e0)
        /usr/lib/golang/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82003e000, 0xc820128000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7fbbc2e16000, 0xc82003e000, 0xc82022a108, 0xc820128000, 0x1000, 0x1000, 0xc8248c9200, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8202f49a0, 0xc820128000, 0x1000, 0x1000, 0xc82609d93e, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8248c90e0)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8248c90e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82022a0b0)
        /usr/lib/golang/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:685 +0xc78

goroutine 1659185 [select]:
net/http.(*persistConn).roundTrip(0xc82022a0b0, 0xc82609d7e0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1164 +0xb0d
net/http.(*Transport).RoundTrip(0xc82000a240, 0xc82016e1c0, 0xba, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:235 +0x530
net/http.send(0xc82016e1c0, 0x7fbbc5e404d8, 0xc82000a240, 0xc8201acc40, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:220 +0x52c
net/http.(*Client).send(0xc24540, 0xc82016e1c0, 0x62, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:143 +0x15a
net/http.(*Client).doFollowingRedirects(0xc24540, 0xc82016e1c0, 0xa71dc8, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:380 +0xbc0
net/http.(*Client).Do(0xc24540, 0xc82016e1c0, 0x1e3, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:178 +0x188
github.com/aws/aws-sdk-go/aws/corehandlers.glob.func2(0xc821672580)
        /opt/go/src/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go:65 +0x55
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc8216726b0, 0xc821672580)
        /opt/go/src/github.com/aws/aws-sdk-go/aws/request/handlers.go:115 +0x9f
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc821672580, 0x0, 0x0)
        /opt/go/src/github.com/aws/aws-sdk-go/aws/request/request.go:225 +0x57c
github.com/aws/aws-sdk-go/service/s3.(*S3).UploadPart(0xc8201d8028, 0xc82483b3e0, 0x1, 0x0, 0x0)
        /opt/go/src/github.com/aws/aws-sdk-go/service/s3/api.go:1586 +0x4f
github.com/kahing/goofys/internal.(*FileHandle).mpuPartNoSpawn(0xc8202d01a0, 0xc8200ae400, 0xc820900000, 0x500000, 0x500000, 0x270f, 0x0, 0x0)
        /opt/go/src/github.com/kahing/goofys/internal/handles.go:396 +0x4c3
github.com/kahing/goofys/internal.(*FileHandle).mpuPart(0xc8202d01a0, 0xc8200ae400, 0xc820900000, 0x500000, 0x500000, 0x270f)
        /opt/go/src/github.com/kahing/goofys/internal/handles.go:424 +0xca
created by github.com/kahing/goofys/internal.(*FileHandle).WriteFile
        /opt/go/src/github.com/kahing/goofys/internal/handles.go:492 +0x919

goroutine 1658917 [select]:
net/http.(*persistConn).roundTrip(0xc82022a000, 0xc8203c9ee0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1164 +0xb0d
net/http.(*Transport).RoundTrip(0xc82000a240, 0xc82016e0e0, 0xba, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:235 +0x530
net/http.send(0xc82016e0e0, 0x7fbbc5e404d8, 0xc82000a240, 0xc82023c5b0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:220 +0x52c
net/http.(*Client).send(0xc24540, 0xc82016e0e0, 0x62, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:143 +0x15a
net/http.(*Client).doFollowingRedirects(0xc24540, 0xc82016e0e0, 0xa71dc8, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:380 +0xbc0
net/http.(*Client).Do(0xc24540, 0xc82016e0e0, 0x1e3, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:178 +0x188
github.com/aws/aws-sdk-go/aws/corehandlers.glob.func2(0xc821672000)
        /opt/go/src/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go:65 +0x55
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc821672130, 0xc821672000)
        /opt/go/src/github.com/aws/aws-sdk-go/aws/request/handlers.go:115 +0x9f
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc821672000, 0x0, 0x0)
        /opt/go/src/github.com/aws/aws-sdk-go/aws/request/request.go:225 +0x57c
github.com/aws/aws-sdk-go/service/s3.(*S3).UploadPart(0xc8201d8028, 0xc820298240, 0x1, 0x0, 0x0)
        /opt/go/src/github.com/aws/aws-sdk-go/service/s3/api.go:1586 +0x4f
github.com/kahing/goofys/internal.(*FileHandle).mpuPartNoSpawn(0xc8202d01a0, 0xc8200ae400, 0xc8210d4000, 0x500000, 0x500000, 0x270d, 0x0, 0x0)
        /opt/go/src/github.com/kahing/goofys/internal/handles.go:396 +0x4c3
github.com/kahing/goofys/internal.(*FileHandle).mpuPart(0xc8202d01a0, 0xc8200ae400, 0xc8210d4000, 0x500000, 0x500000, 0x270d)
        /opt/go/src/github.com/kahing/goofys/internal/handles.go:424 +0xca
created by github.com/kahing/goofys/internal.(*FileHandle).WriteFile
        /opt/go/src/github.com/kahing/goofys/internal/handles.go:492 +0x919

goroutine 1659270 [select]:
net/http.(*persistConn).roundTrip(0xc82012c210, 0xc826148cb0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1164 +0xb0d
net/http.(*Transport).RoundTrip(0xc82000a240, 0xc8200b02a0, 0xbb, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:235 +0x530
net/http.send(0xc8200b02a0, 0x7fbbc5e404d8, 0xc82000a240, 0xc8248ee380, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:220 +0x52c
net/http.(*Client).send(0xc24540, 0xc8200b02a0, 0x63, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:143 +0x15a
net/http.(*Client).doFollowingRedirects(0xc24540, 0xc8200b02a0, 0xa71dc8, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:380 +0xbc0
net/http.(*Client).Do(0xc24540, 0xc8200b02a0, 0x1e4, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:178 +0x188
github.com/aws/aws-sdk-go/aws/corehandlers.glob.func2(0xc82486e000)
        /opt/go/src/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go:65 +0x55
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc82486e130, 0xc82486e000)
        /opt/go/src/github.com/aws/aws-sdk-go/aws/request/handlers.go:115 +0x9f
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc82486e000, 0x0, 0x0)
        /opt/go/src/github.com/aws/aws-sdk-go/aws/request/request.go:225 +0x57c
github.com/aws/aws-sdk-go/service/s3.(*S3).UploadPart(0xc8201d8028, 0xc8216d80c0, 0x1, 0x0, 0x0)
        /opt/go/src/github.com/aws/aws-sdk-go/service/s3/api.go:1586 +0x4f
github.com/kahing/goofys/internal.(*FileHandle).mpuPartNoSpawn(0xc8202d01a0, 0xc8200ae400, 0xc8203de000, 0x500000, 0x500000, 0x2710, 0x0, 0x0)
        /opt/go/src/github.com/kahing/goofys/internal/handles.go:396 +0x4c3
github.com/kahing/goofys/internal.(*FileHandle).mpuPart(0xc8202d01a0, 0xc8200ae400, 0xc8203de000, 0x500000, 0x500000, 0x2710)
        /opt/go/src/github.com/kahing/goofys/internal/handles.go:424 +0xca
created by github.com/kahing/goofys/internal.(*FileHandle).WriteFile
        /opt/go/src/github.com/kahing/goofys/internal/handles.go:492 +0x919

goroutine 1657418 [IO wait]:
net.runtime_pollWait(0x7fbbc5e41ed8, 0x72, 0xc8200101e0)
        /usr/lib/golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203a9560, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203a9560, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203a9500, 0xc823b68000, 0x1000, 0x1000, 0x0, 0x7fbbc5e3c050, 0xc8200101e0)
        /usr/lib/golang/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82024c028, 0xc823b68000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7fbbc2e16000, 0xc82024c028, 0xc82022a058, 0xc823b68000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8202e30a0, 0xc823b68000, 0x1000, 0x1000, 0xc8200bc760, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82608aae0)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82608aae0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82022a000)
        /usr/lib/golang/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:685 +0xc78

goroutine 1654922 [select]:
net/http.(*persistConn).writeLoop(0xc82012c210)
        /usr/lib/golang/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:686 +0xc9d

goroutine 1657419 [select]:
net/http.(*persistConn).writeLoop(0xc82022a000)
        /usr/lib/golang/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:686 +0xc9d

goroutine 1659055 [select]:
net/http.(*persistConn).writeLoop(0xc82022a0b0)
        /usr/lib/golang/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:686 +0xc9d

goroutine 1659557 [runnable]:
fmt.(*fmt).padString(0xc8200741f8, 0xc0377f, 0xd)
        /usr/lib/golang/src/fmt/format.go:130 +0x406
fmt.(*fmt).fmt_s(0xc8200741f8, 0xc0377f, 0xd)
        /usr/lib/golang/src/fmt/format.go:322 +0x61
fmt.(*pp).fmtString(0xc8200741a0, 0xc0377f, 0xd, 0xc800000076)
        /usr/lib/golang/src/fmt/print.go:518 +0x144
fmt.(*pp).printArg(0xc8200741a0, 0x7ffee0, 0xc821640450, 0x76, 0x0, 0x0)
        /usr/lib/golang/src/fmt/print.go:797 +0xd91
fmt.(*pp).doPrintf(0xc8200741a0, 0x982140, 0x5, 0xc8208f3d10, 0x2, 0x2)
        /usr/lib/golang/src/fmt/print.go:1219 +0x1dd8
fmt.Sprintf(0x982140, 0x5, 0xc8208f3d10, 0x2, 0x2, 0x0, 0x0)
        /usr/lib/golang/src/fmt/print.go:203 +0x6f
github.com/jacobsa/fuse.(*Connection).debugLog(0xc820252000, 0x186aa8, 0x1, 0x9823d0, 0x5, 0x0, 0x0, 0x0)
        /opt/go/src/github.com/jacobsa/fuse/connection.go:196 +0x20f
github.com/jacobsa/fuse.(*Connection).Reply(0xc820252000, 0x7fbbc0f93128, 0xc824849380, 0x0, 0x0)
        /opt/go/src/github.com/jacobsa/fuse/connection.go:474 +0x3d0
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc820144420, 0xc820252000, 0x7fbbc0f93128, 0xc824849380, 0x7dde40, 0xc824849200)
        /opt/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:191 +0x183
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
        /opt/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:108 +0x18f

goroutine 1654921 [IO wait]:
net.runtime_pollWait(0x7fbbc5e41f98, 0x72, 0xc8200101e0)
        /usr/lib/golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200de290, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200de290, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200de230, 0xc82023f000, 0x1000, 0x1000, 0x0, 0x7fbbc5e3c050, 0xc8200101e0)
        /usr/lib/golang/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82003e040, 0xc82023f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7fbbc2e16000, 0xc82003e040, 0xc82012c268, 0xc82023f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820244520, 0xc82023f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8200be720)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8200be720, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82012c210)
        /usr/lib/golang/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:685 +0xc78
```

**Comment by kahing** [comment] 2015-12-17 02:49
duplicate of #20

**Closed by kahing** 2015-12-17 02:49 UTC
